version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: genlitedb
      MYSQL_USER: genliteuser
      MYSQL_PASSWORD: genlitepass

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db   
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 330
      UPLOAD_LIMIT: 1000M
  
  # PHP / WordPress 
  wordpress:
    image: wordpress:latest
    depends_on:
      - db   
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/genlite
      - ./plugins:/var/www/html/wp-content/plugins
      - ./docker-php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: genliteuser
      WORDPRESS_DB_PASSWORD: genlitepass
      WORDPRESS_DB_NAME: genlitedb
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1

volumes:
  wordpress:
  db:
